blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),

    path('index.html', views.index, name='index'),
    path('archive.html', views.archives, name='archives'),
    path('techtips.html', views.techtips, name='tips'),
    path('about.html', views.about, name='about'),
    path('<int:blog_id>/', views.entry, name='entry'),
    path('<int:blog_id>/comment/', views.comment, name='comment'),
]

cs2610proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls)

]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

blog/models.py
from django.db import models
import datetime
from django.utils import timezone


class Blog(models.Model):
    title = models.CharField(max_length=60)
    author = models.CharField(max_length=30)
    content = models.TextField(max_length=2000)
    posted = models.DateTimeField('date published')

    def __str__(self):
        return self.title


class Comments(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    commenter = models.CharField(max_length=30)
    email = models.EmailField()
    content = models.TextField(max_length=1000)
    posted = models.DateTimeField('date published')

    def __str__(self):
        return self.commenter

polls/models.py
from django.db import models
import datetime
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

blog/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .models import Blog, Comments
from django.urls import reverse


def index(request):
    latest_posts_list = Blog.objects.order_by('-posted')[:3]
    context = {'latest_posts_list': latest_posts_list}
    return render(request, 'blog/index.html', context)


def techtips(request):
    context = {'time': timezone.now()}
    return render(request, 'blog/techtips.html', context)


def about(request):
    context = {'time': timezone.now()}
    return render(request, 'blog/about.html', context)


def archives(request):
    posts_list = Blog.objects.order_by('-posted')
    context = {'posts_list': posts_list}
    return render(request, 'blog/archive.html', context)


def entry(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)

    return render(request, 'blog/entry.html', {'blog': blog})


def comment(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    try:
        commenter = request.POST['commenter']
        email = request.POST['email']
        contents = request.POST['comment_content']
        posted = timezone.now()
        newComment = Comments(blog_id=blog_id, commenter=commenter, email=email, content=contents, posted=posted)
        newComment.save()
    except (KeyError, Comments.DoesNotExist):
        pass
        # something might go here
    return HttpResponseRedirect(reverse('blog:entry', args=(blog.id,)))

polls/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.http import HttpResponse, Http404
from .models import Question


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)


def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

blog/templates/blog/about.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="stylesheet" href="{% static 'blog/style.css' %}" type="text/css">
  <title>Blog</title>
</head>

<body>
  <div id="links">
    <a href="{% url 'blog:index'%}">Home</a>
    <a href="{% url 'blog:archives'%}">Archives</a>
    <a href="{% url 'blog:about'%}">About Me</a>
    <a href="{% url 'blog:tips'%}">Tech Tips</a>
  </div>


  <div id="content">
    <div>Time: {{ time }}</div>
    <h1>About Me</h1>
    <img src="{% static 'blog/portrait.jpg' %}" alt=""/>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
       incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
       quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
       consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
       cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
       proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
  </div>



</body>

</html>

blog/templates/blog/archive.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="stylesheet" href="{% static 'blog/style.css' %}" type="text/css">
  <title>Blog</title>
</head>

<body>
  <div id="links">
    <a href="{% url 'blog:index'%}">Home</a>
    <a href="{% url 'blog:archives'%}">Archives</a>
    <a href="{% url 'blog:about'%}">About Me</a>
    <a href="{% url 'blog:tips'%}">Tech Tips</a>
  </div>

  <div id="content">
    <h1>Blog Archive</h1>
    {% if posts_list %}
      {% for blog in posts_list %}
        <a href="{% url 'blog:entry' blog.id %}">
          <div class="blogpost">
            <h2>{{blog.title}}</h2>
            <h5>{{blog.author}}, {{blog.posted}}</h5>
            <p>
              {{blog.content|truncatewords:100}}
            </p>
            <p>
              <p>
              <strong>{{blog.comments_set.all|length}} comment{{blog.comments_set.all|pluralize}}</strong>
              </p>
            </p>
          </div>
        </a>
      {% endfor %}
    {% else %}
      <p>No posts are available.</p>
    {% endif %}
  </div>
</body>

</html>

blog/templates/blog/entry.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}" type="text/css">
</head>
<body>
    <div id="links">
        <a href="{% url 'blog:index'%}">Home</a>
        <a href="{% url 'blog:archives'%}">Archives</a>
        <a href="{% url 'blog:about'%}">About Me</a>
        <a href="{% url 'blog:tips'%}">Tech Tips</a>
    </div>
    <div id="content">
        <h1>Blog</h1>
        <div class="blogpost">
          <h2>{{blog.title}}</h2>
          <h5>{{blog.author}}, {{blog.posted}}</h5>
          <p>
            {{blog.content}}
          </p>
        </div>

        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <form action="{% url 'blog:comment' blog.id %}", method="post">
            {% csrf_token %}
            <label for="name">Your name: </label>
            <input id="name" type="text" name="commenter">
            <br>
            <label for="email">Your email: </label>
            <input id="email" type="text" name="email">
            <br>
            <label for="comment_content">Your comment: </label>
            <input id="comment_content" type="text" name="comment_content">
            <br>
            <input type="submit" value="OK">


        </form>
        {% if blog.comments_set.all %}
        <h2>Comments:</h2>
            {% for comment in blog.comments_set.all reversed %}
            <div class="blogpost">
                <h2>{{comment.title}}</h2>
                <h5>{{comment.commenter}}, {{comment.email}}, {{comment.posted}}</h5>
                <p>
                {{comment.content}}
                </p>
            </div>
            {%endfor%}
        {% else %}
        <h2>There are no comments</h2>
        {% endif%}
    </div>
</body>
</html>

blog/templates/blog/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="stylesheet" href="{% static 'blog/style.css' %}" type="text/css">
  <title>Blog</title>
</head>

<body>
  <div id="links">
    <a href="{% url 'blog:index'%}">Home</a>
    <a href="{% url 'blog:archives'%}">Archives</a>
    <a href="{% url 'blog:about'%}">About Me</a>
    <a href="{% url 'blog:tips'%}">Tech Tips</a>
  </div>
  <div id="content">
    <h1>Blog Home</h1>
    <h2>Most recent posts:</h2>
    {% if latest_posts_list %}
      {% for blog in latest_posts_list %}
        <a id="blog_post_link", href="{% url 'blog:entry' blog.id %}">
          <div class="blogpost">
            <h2>{{blog.title}}</h2>
            <h5>{{blog.author}}, {{blog.posted}}</h5>
            <p>
              {{blog.content|truncatewords:100}}
            </p>
            <p>
              <strong>{{blog.comments_set.all|length}} comment{{blog.comments_set.all|pluralize}}</strong>
            </p>
          </div>
        </a>
      {% endfor %}
    {% else %}
      <p>No posts are available.</p>
    {% endif %}
  </div>
</body>

</html>

blog/templates/blog/techtips.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="stylesheet" href="{% static 'blog/style.css' %}" type="text/css">
  <title>Fred's Blog</title>
</head>

<body>
  <div id="links">
    <a href="{% url 'blog:index'%}">Home</a>
    <a href="{% url 'blog:archives'%}">Archives</a>
    <a href="{% url 'blog:about'%}">About Me</a>
    <a href="{% url 'blog:tips'%}">Tech Tips</a>
  </div>


  <div id="content">
    <div>Time: {{ time }}</div>
    <h1>Tech Tips</h1>
    <p>Here are some descriptions of elements, entities, selectors, and properties in HTML and CSS</p>

    <div class="blogpost">
      <h2>HTML Elements</h2>
      <ul>
        <li><span class="element">&#60;html&#62;:</span>
          The <span class="element">&#60;html&#62;</span> element is used to start and end documents.
          This element lets the browser know where to start and stop reading the file. It is neither inline, nor block-level.</li>
        <li><span class="element">&#60;head&#62;:</span>
          The <span class="element">&#60;head&#62;</span> element contains information about the document, like its title, the meta element, and
          any linked documents like CSS or JS files. It is neither inline, nor block-level.
        </li>
        <li><span class="element">&#60;title&#62;:</span>
          The <span class="element">&#60;title&#62;</span> element gives a title to the document that appears on the top of the browser.
          It is neither inline, nor block-level.
        </li>
        <li><span class="element">&#60;meta&#62;:</span>
          The <span class="element">&#60;meta&#62;</span> element defines metadata about the HTML doc. Nothing in this tag is displayed,
          it is just information for the browser. It is neither inline, nor block-level.
        </li>
        <li><span class="element">&#60;link&#62;:</span>
          The <span class="element">&#60;link&#62;</span> element links other documents, like CSS or JS documents to your HTML doc in order to
          use the files together, for formatting or other uses. It is neither inline, nor block-level.
        </li>
        <li><span class="element">&#60;body&#62;:</span>
          The <span class="element">&#60;body&#62;</span> tag contains all of the displayed content for your page. Everything you see on the screen
          in a webpage is contained in the body. It is neither inline, nor block-level.
        </li>
        <li><span class="element">&#60;div&#62;:</span>
          The <span class="element">&#60;div&#62;</span> tag identifies a section of the document in order to group things or make changes to
          chunks of the document at once. It's often used for styling its contents. It is considered a block-level element.
        </li>
        <li><span class="element">&#60;p&#62;:</span>
          The <span class="element">&#60;p&#62;</span> element denotes a paragraph, and ignores extra spaces and tabs in its contents.
          It is considered a block-level element.
        </li>
        <li><span class="element">&#60;ol&#62;:</span>
          The <span class="element">&#60;ol&#62;</span> element creates an ordered list, numbering each line item.
          These lists contain <span class="element">&#60;li&#62;</span> tags. It is considered a block-level element.
        </li>
        <li><span class="element">&#60;ul&#62;:</span>
          The <span class="element">&#60;ul&#62;</span> tag creates an unordered list, like the one we are currently using, with each item starting with a dot by default.
          These lists contain <span class="element">&#60;li&#62;</span> tags. It is considered a block-level element.
        </li>
        <li><span class="element">&#60;li&#62;:</span>
          These tags are only used within lists, both ordered and unordered. It is considered a block-level element.
        </li>
        <li><span class="element">&#60;img&#62;:</span>
          The <span class="element">&#60;img&#62;</span> elements are used to link an image into an HTML document. These tags are empty, meaning they have
          no closing tags. It is considered an inline element.
        </li>
      </ul>
    </div>

    <div class="blogpost">
      <h2>HTML Entities</h2>
      <ul>
        <li><span class="element">&#60;</span> is the less than entity. It is used in HTML to denote the beginning of a tag.</li>
        <li><span class="element">&#62;</span> is the greater than entity. It is used in HTML to denote the end of a tag.</li>
      </ul>
    </div>

    <div class="blogpost">
      <h2>CSS Selectors</h2>
      <ul>
        <li><span class="italic">Element</span> selectors choose specific elements used in a document, and modify the appearence of
          these elements. In this website, the element selector for img is used to modify all images on the site. I also use it to
          select all of the <span class="element">&#60;li&#62;</span> tags, and then choose every other tag to change their colors
          with the nth-child pseudo-selector.</li>
        <li><span class="italic">Class</span> selectors select specific classes used to identify certain tags in the document.
          Classes are applied to tags in the attributes section, and are selected in CSS by using a period followed by the class name.
          In this document, each section of the page is identified by a blogpost class name, so each section can be formatted the same.
        </li>
        <li><span class="italic">ID</span> selectors select specific IDs used to identify a particular tag in the document.
          An ID can be applied to a tag in the attributes section just like classes, and are selected in CSS by using a #,
          followed by the ID name. In this website, the content div on each page is selected by the content ID</li>
      </ul>
    </div>
    <div class="blogpost">
      <h2>CSS Properties</h2>
      <ul>
        <li>background-color: The background color property determines the color behind the selected HTML element.
          Any color in hex format can be used, or some common strings describing colors. </li>
        <li>color: The color property determines text color within an HTML elemnt. The same values can be taken as for the background-color property. </li>
        <li>font-family: The font family property allows you to select the family of fonts for a given element, changing the text within that element.
          Families include serif, sans-serif, or even times or courier. If the default font for said family doesn't work in a browser,
          it will choose another from the same family.</li>
        <li>font-style: The font-style property allows you to make the text in an element italic or oblique (leaning).</li>
        <li>font-size: The font-size property allows you to change the size of text within an element. Font sizes can be entered as a number, followed by pt,
          or in several other formats that are less frequently used. </li>
        <li>margin: The margin property allows you to create space around an element where other elements can't enter.
          This helps create whitespace in the design of a page. Values can be accepted in pixels or even percentages of the page size for this property.</li>
        <li>padding: The padding tag creates space inside of an element between the edge of the element and child elements. Acceptable values for padding are the same as margin</li>
        <li>width: The width property lets you fix the width of an element to a certain number of pixels or a percentage of the screen size.</li>
        <li>border-width: The border-width property allows you to specify the width of a border around the element. This can be given in pixels (px).</li>
        <li>border-style: The border-style property allows you to customize the kind of border around an element. For example, dotted, inset, or groove.</li>
      </ul>
    </div>

  </div>

</body>
</html>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}